# -*- coding: utf-8 -*-
"""train_chatbotv3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BmcId_k6m3bpfBOu-jjQ4snURfrTzJGY

Chatbot using LSTM
"""

import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

import json
import pickle
import numpy as np

from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import SGD

import random

words = []
classes = []
documents = []
ignore_words = []
data_file = open('intents.json').read()
intents = json.loads(data_file)

